// Display names for language codes (Deepgram, Google, Sarvam, Azure)
export const LANGUAGE_DISPLAY_NAMES: Record<string, string> = {
    "multi": "Multilingual (Auto-detect)",
    "unknown": "Auto-detect",

    // Arabic
    "ar": "Arabic",
    "ar-AE": "Arabic (UAE)",
    "ar-BH": "Arabic (Bahrain)",
    "ar-DZ": "Arabic (Algeria)",
    "ar-EG": "Arabic (Egypt)",
    "ar-IL": "Arabic (Israel)",
    "ar-IQ": "Arabic (Iraq)",
    "ar-IR": "Arabic (Iran)",
    "ar-JO": "Arabic (Jordan)",
    "ar-KW": "Arabic (Kuwait)",
    "ar-LB": "Arabic (Lebanon)",
    "ar-MA": "Arabic (Morocco)",
    "ar-MR": "Arabic (Mauritania)",
    "ar-OM": "Arabic (Oman)",
    "ar-PS": "Arabic (Palestine)",
    "ar-QA": "Arabic (Qatar)",
    "ar-SA": "Arabic (Saudi Arabia)",
    "ar-SD": "Arabic (Sudan)",
    "ar-SY": "Arabic (Syria)",
    "ar-TD": "Arabic (Chad)",
    "ar-TN": "Arabic (Tunisia)",
    "ar-XA": "Arabic (Generic)",
    "ar-YE": "Arabic (Yemen)",

    // English
    "en": "English",
    "en-AU": "English (Australia)",
    "en-GB": "English (UK)",
    "en-HK": "English (Hong Kong)",
    "en-IE": "English (Ireland)",
    "en-IN": "English (India)",
    "en-NZ": "English (New Zealand)",
    "en-PH": "English (Philippines)",
    "en-PK": "English (Pakistan)",
    "en-SG": "English (Singapore)",
    "en-US": "English (US)",

    // Spanish
    "es": "Spanish",
    "es-419": "Spanish (Latin America)",
    "es-AR": "Spanish (Argentina)",
    "es-BO": "Spanish (Bolivia)",
    "es-CL": "Spanish (Chile)",
    "es-CO": "Spanish (Colombia)",
    "es-CR": "Spanish (Costa Rica)",
    "es-DO": "Spanish (Dominican Republic)",
    "es-EC": "Spanish (Ecuador)",
    "es-ES": "Spanish (Spain)",
    "es-GT": "Spanish (Guatemala)",
    "es-HN": "Spanish (Honduras)",
    "es-MX": "Spanish (Mexico)",
    "es-NI": "Spanish (Nicaragua)",
    "es-PA": "Spanish (Panama)",
    "es-PE": "Spanish (Peru)",
    "es-PR": "Spanish (Puerto Rico)",
    "es-SV": "Spanish (El Salvador)",
    "es-US": "Spanish (US)",
    "es-UY": "Spanish (Uruguay)",
    "es-VE": "Spanish (Venezuela)",

    // French
    "fr": "French",
    "fr-BE": "French (Belgium)",
    "fr-CA": "French (Canada)",
    "fr-CH": "French (Switzerland)",
    "fr-FR": "French (France)",

    // German
    "de": "German",
    "de-AT": "German (Austria)",
    "de-CH": "German (Switzerland)",
    "de-DE": "German (Germany)",

    // Portuguese
    "pt": "Portuguese",
    "pt-BR": "Portuguese (Brazil)",
    "pt-PT": "Portuguese (Portugal)",

    // Chinese
    "zh": "Chinese",
    "zh-CN": "Chinese (Simplified)",
    "zh-TW": "Chinese (Traditional)",
    "cmn-CN": "Mandarin (China)",
    "cmn-Hans-CN": "Mandarin (Simplified)",
    "cmn-Hant-TW": "Mandarin (Traditional)",
    "yue-HK": "Cantonese (Hong Kong)",
    "yue-Hant-HK": "Cantonese (Hong Kong, Traditional)",

    // Dutch
    "nl": "Dutch",
    "nl-BE": "Dutch (Belgium)",
    "nl-NL": "Dutch (Netherlands)",

    // Italian
    "it": "Italian",
    "it-CH": "Italian (Switzerland)",
    "it-IT": "Italian (Italy)",

    // Indian Languages
    "as-IN": "Assamese",
    "bn-IN": "Bengali (India)",
    "bn-BD": "Bengali (Bangladesh)",
    "gu-IN": "Gujarati",
    "hi-IN": "Hindi",
    "kn-IN": "Kannada",
    "ml-IN": "Malayalam",
    "mr-IN": "Marathi",
    "od-IN": "Odia",
    "or-IN": "Odia (India)",
    "pa-IN": "Punjabi (India)",
    "pa-Guru-IN": "Punjabi (Gurmukhi)",
    "ta-IN": "Tamil (India)",
    "te-IN": "Telugu (India)",
    "ur-IN": "Urdu (India)",
    "ur-PK": "Urdu (Pakistan)",
    "ne-IN": "Nepali (India)",
    "ne-NP": "Nepali (Nepal)",
    "kok-IN": "Konkani",
    "ks-IN": "Kashmiri",
    "sd-IN": "Sindhi (India)",
    "sa-IN": "Sanskrit",
    "sat-IN": "Santali",
    "mni-IN": "Manipuri",
    "brx-IN": "Bodo",
    "mai-IN": "Maithili",
    "doi-IN": "Dogri",

    // African Languages
    "af-ZA": "Afrikaans (South Africa)",
    "am-ET": "Amharic (Ethiopia)",
    "ha-NG": "Hausa (Nigeria)",
    "ig-NG": "Igbo (Nigeria)",
    "kam-KE": "Kamba (Kenya)",
    "lg-UG": "Luganda (Uganda)",
    "ln-CD": "Lingala (Congo)",
    "luo-KE": "Luo (Kenya)",
    "nso-ZA": "Northern Sotho (South Africa)",
    "ny-MW": "Chichewa (Malawi)",
    "om-ET": "Oromo (Ethiopia)",
    "rw-RW": "Kinyarwanda (Rwanda)",
    "sn-ZW": "Shona (Zimbabwe)",
    "so-SO": "Somali (Somalia)",
    "ss-Latn-ZA": "Swazi (South Africa)",
    "st-ZA": "Southern Sotho (South Africa)",
    "sw": "Swahili",
    "sw-KE": "Swahili (Kenya)",
    "tn-Latn-ZA": "Tswana (South Africa)",
    "ts-ZA": "Tsonga (South Africa)",
    "umb-AO": "Umbundu (Angola)",
    "ve-ZA": "Venda (South Africa)",
    "wo-SN": "Wolof (Senegal)",
    "xh-ZA": "Xhosa (South Africa)",
    "yo-NG": "Yoruba (Nigeria)",
    "zu-ZA": "Zulu (South Africa)",

    // Asian Languages
    "bn": "Bengali",
    "ja": "Japanese",
    "ja-JP": "Japanese (Japan)",
    "ko": "Korean",
    "ko-KR": "Korean (South Korea)",
    "th": "Thai",
    "th-TH": "Thai (Thailand)",
    "vi": "Vietnamese",
    "vi-VN": "Vietnamese (Vietnam)",
    "id": "Indonesian",
    "id-ID": "Indonesian (Indonesia)",
    "ms": "Malay",
    "ms-MY": "Malay (Malaysia)",
    "tl": "Tagalog",
    "fil-PH": "Filipino (Philippines)",
    "jv-ID": "Javanese (Indonesia)",
    "su-ID": "Sundanese (Indonesia)",
    "ceb-PH": "Cebuano (Philippines)",
    "km-KH": "Khmer (Cambodia)",
    "lo-LA": "Lao (Laos)",
    "my-MM": "Burmese (Myanmar)",
    "si-LK": "Sinhala (Sri Lanka)",
    "mn-MN": "Mongolian (Mongolia)",

    // European Languages
    "be": "Belarusian",
    "be-BY": "Belarusian (Belarus)",
    "bg": "Bulgarian",
    "bg-BG": "Bulgarian (Bulgaria)",
    "bs": "Bosnian",
    "bs-BA": "Bosnian (Bosnia)",
    "ca": "Catalan",
    "ca-ES": "Catalan (Spain)",
    "cs": "Czech",
    "cs-CZ": "Czech (Czech Republic)",
    "cy-GB": "Welsh (Wales)",
    "da": "Danish",
    "da-DK": "Danish (Denmark)",
    "el": "Greek",
    "el-GR": "Greek (Greece)",
    "et": "Estonian",
    "et-EE": "Estonian (Estonia)",
    "eu-ES": "Basque (Spain)",
    "fi": "Finnish",
    "fi-FI": "Finnish (Finland)",
    "ga-IE": "Irish (Ireland)",
    "gl-ES": "Galician (Spain)",
    "hr": "Croatian",
    "hr-HR": "Croatian (Croatia)",
    "hu": "Hungarian",
    "hu-HU": "Hungarian (Hungary)",
    "hy-AM": "Armenian (Armenia)",
    "is-IS": "Icelandic (Iceland)",
    "ka-GE": "Georgian (Georgia)",
    "kk-KZ": "Kazakh (Kazakhstan)",
    "ky-KG": "Kyrgyz (Kyrgyzstan)",
    "lb-LU": "Luxembourgish (Luxembourg)",
    "lt": "Lithuanian",
    "lt-LT": "Lithuanian (Lithuania)",
    "lv": "Latvian",
    "lv-LV": "Latvian (Latvia)",
    "mi-NZ": "Māori (New Zealand)",
    "mk": "Macedonian",
    "mk-MK": "Macedonian (North Macedonia)",
    "mt-MT": "Maltese (Malta)",
    "no": "Norwegian",
    "no-NO": "Norwegian (Norway)",
    "nb-NO": "Norwegian Bokmål (Norway)",
    "oc-FR": "Occitan (France)",
    "pl": "Polish",
    "pl-PL": "Polish (Poland)",
    "ro": "Romanian",
    "ro-RO": "Romanian (Romania)",
    "rup-BG": "Aromanian (Bulgaria)",
    "ru": "Russian",
    "ru-RU": "Russian (Russia)",
    "sk": "Slovak",
    "sk-SK": "Slovak (Slovakia)",
    "sl": "Slovenian",
    "sl-SI": "Slovenian (Slovenia)",
    "sq-AL": "Albanian (Albania)",
    "sr": "Serbian",
    "sr-RS": "Serbian (Serbia)",
    "sv": "Swedish",
    "sv-SE": "Swedish (Sweden)",
    "tg-TJ": "Tajik (Tajikistan)",
    "tr": "Turkish",
    "tr-TR": "Turkish (Turkey)",
    "uk": "Ukrainian",
    "uk-UA": "Ukrainian (Ukraine)",
    "ur": "Urdu",
    "uz": "Uzbek",
    "uz-UZ": "Uzbek (Uzbekistan)",

    // Middle Eastern Languages
    "az-AZ": "Azerbaijani (Azerbaijan)",
    "ckb-IQ": "Central Kurdish (Iraq)",
    "fa": "Persian",
    "fa-IR": "Persian (Iran)",
    "ff-SN": "Fulah (Senegal)",
    "he": "Hebrew",
    "he-IL": "Hebrew (Israel)",
    "iw-IL": "Hebrew (Israel)",
    "kea-CV": "Kabuverdianu (Cape Verde)",
    "ps-AF": "Pashto (Afghanistan)",

    // Other Languages
    "ast-ES": "Asturian (Spain)",
    "ba": "Bashkir",
    "bo": "Tibetan",
    "br": "Breton",
    "fo": "Faroese",
    "ht": "Haitian Creole",
    "haw": "Hawaiian",
    "jw": "Javanese",
    "la": "Latin",
    "mg": "Malagasy",
    "tt": "Tatar",
    "yi": "Yiddish",
};
